### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [seandstewart/redis-py-sansio#2]
I think we should also include a performance benchmark of redis-py sync, pre-SansIO. Others will want to compare aredis as well...

**Comment by seandstewart** [comment]
Couldn't agree more. I think a real benchmark suite would be excellent. Tricky given how this repo is namespaced, but since this is meant to be a demonstration we could change the root package name so we can install redis-py without conflicts

**Comment by Andrew-Chen-Wang** [comment]
Perhaps in your virtualenv if you have one locally rather than in a docker container, you could rename one of the redis packages to something different then install the other redis package. Not sure if that's how simple it is though.

Otherwise, I think another option would be to pip install from http and specify an egg.

**Comment by seandstewart** [comment]
This is done! I renamed this source's package so I could get redis-py installed. The benchmark suite is still performing the same get/set test. Would be worthwhile to expand to testing a pipeline too.
